python   3.10.14
torch   2.1.2+cu118
torch-cluster   1.6.3+pt21cu118
torch-geometric   2.3.0
torch-scatter   2.1.2+pt21cu118
torch-sparse   0.6.18+pt21cu118
torch-spline-conv   1.2.2+pt21cu118
torchaudio   2.1.2+cu118
torchmetrics   1.4.0.post0
torchsummary   1.5.1
torchvision   0.16.2+cu118
numpy   1.26.4
pandas   2.2.2
scikit-learn   1.5.1
scipy   1.14.0